name: Build and deploy a container to a remote server

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: self-hosted

        steps:
            - name: Copy Repository
              uses: actions/checkout@v4
              
            - name: Running Docker Compose
              run: docker compose up -d --build
